name: ZLOBBY
version: '1.5-SNAPSHOT'
main: com.john4096.zLOBBY.ZLOBBY
api-version: '1.17'
authors: [ JohnRichard4096 ]
description: Plugin for ZCRAFT ONLY

commands:
  zlobby:
    description: "ZCRAFT Lobby plugin main command"
    usage: /<command> <subcommand>
    aliases: [ zlo,zl,ZLOBBY ]
    permission: "zlobby.main"
    permission-message: "You have no permission to use this command!"

  zlobby.reload:
    description: "Reload the config file"
    usage: /<command> reload
    permission: "zlobby.main.reload"
    permission-message: "You have no permission to use this command!"

  zlobby.info:
    description: "Get ZLobby info"
    usage: /<command> info
    permission: "zlobby.main.info"
    permission-message: "You have no permission to use this command!"

permissions:
  zlobby.main:
    description: "Allow to use /<command> (not all sub command)"
    default: true
    children:
      zlobby.main.info: true
  zlobby.main.*:
    description: "Allow to use all commands"
    children:
      zlobby.main.reload: true
      zlobby.main.info: true
      zlobby.main.info.more: true
      zlobby.main.debugger: true
    default: false
  zlobby.main.debugger:
    description: "Allow to use /<command> debugger"
    default: op
  zlobby.*:
    description: "Own all permissions(We don't suppose you to let ANY player to own this permission!!!)"
    children:
      zlobby.main: true
      zlobby.main.*: true
      zlobby.effect: true
      zlobby.lobby.*: true
    default: false

  zlobby.main.reload:
    description: "Allow to reload ZLobby"
    default: op
  zlobby.main.info:
    description: "Allow to get ZLobby info"
    default: true
  zlobby.main.info.more:
    description: "Allow to get more ZLobby info"
    default: op

  zlobby.lobby.*:
    description: "Give this player all permission even including some special permissions!"
    children:
      zlobby.lobby.tp: false
      zlobby.lobby.feed: true
      zlobby.lobby.health: true
      zlobby.lobby.break: true
      zlobby.lobby.place: true
      zlobby.lobby.noChangeMode: true
      zlobby.lobby.neverKick: true
    default: false
  zlobby.lobby.noChangeMode:
    description: "Do not change this player's game mode by this plugin."
    default: false
  zlobby.lobby.tp:
    description: "Allow to teleport this player to safe place"
    default: true
  zlobby.lobby.feed:
    description: "Allow to feed this player"
    default: true
  zlobby.lobby.health:
    description: "Allow to heal this player"
    default: true
  zlobby.lobby.break:
    description: "Allow to break blocks in lobby"
    default: false
  zlobby.lobby.place:
    description: "Allow to place blocks in lobby"
    default: false
  zlobby.effect:
    description: "Allow to spawn fireworks/title/subtitle/sound to this player."
    default: true
  zlobby.lobby.neverKick:
    description: "Do not kick this player when he/she try to break blocks in lobby."
    default: false
  zlobby.lobby.message:
    description: "Player will receive welcome messages."
    default: true