name: ZLOBBY
version: '1.2-SNAPSHOT'
main: com.john4096.zLOBBY.ZLOBBY
api-version: '1.17'
authors: [ JohnRichard4096 ]
description: Plugin for ZCRAFT ONLY

commands:
  zlobby:
    description: "ZCRAFT Lobby plugin main command"
    usage: /<command> <subcommand>
    aliases: [zlo,zl,ZLOBBY]
    permission: "zlobby.main"
    permission-message: "You have no permission to use this command!"

  zlobby.reload:
    description: "Reload the config file"
    usage: /<command> reload
    permission: "zlobby.main.reload"
    permission-message: "You have no permission to use this command!"

  zlobby.info:
    description: "Get ZLobby info"
    usage: /<command> info
    permission: "zlobby.main.info"
    permission-message: "You have no permission to use this command!"

permissions:
  zlobby.main:
    description: "Allow to use /<command> (not all sub command)"
    default: true
    children:
      zlobby.main.info: true
  zlobby.main.*:
    description: "Allow to use all commands"
    children:
      zlobby.main.reload: true
      zlobby.main.info: true
      zlobby.main.info.more: true
    default: false
  zlobby.*:
    description: "Own all permissions"
    children:
      zlobby.main: true
      zlobby.main.*: true
      zlobby.lobby.changeMode: true
      zlobby.lobby.break: true
      zlobby.lobby.place: true
    default: false

  zlobby.main.reload:
    description: "Allow to reload ZLobby"
    default: op
  zlobby.main.info:
    description: "Allow to get ZLobby info"
    default: true
  zlobby.main.info.more:
    description: "Allow to get more ZLobby info"
    default: op
  zlobby.lobby.*:
    description: "Give all admin-like permission in ZLobby"
    children:
      zlobby.lobby.noChangeMode: true
      zlpobby.lobby.break: true
      zlobby.lobby.place: true
      zlobby.lobby.neverKick: true
      zlobby.lobby.tp: false
      zlobby.lobby.feed: true
      zlobby.lobby.health: true
    default: false
  zlobby.lobby.noChangeMode:
    description: "Not change player's mode"
    default: false
  zlobby.lobby.break:
    description: "Allow to break block"
    default: op
  zlobby.lobby.place:
    description: "Allow to place block"
    default: op
  zlobby.lobby.neverKick:
    description: "Never kick this player"
    default: false
  zlobby.tp:
    description: "Could tp this player"
    default: true
  zlobby.feed:
    description: "Could feed this player"
    default: true
  zlobby.health:
    description: "Could heal HP with this player"
    default: true